name: Test Email from Gmail

on:
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Select test type'
        required: true
        type: choice
        options:
          - Success Test
          - Failure Test
          - Timeout Test
          - Unknown Test

jobs:
  test-email-gmail:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Prepare Test Email Content
        run: |
          TEST_TYPE="${{ inputs.test_type }}"
          if [ "$TEST_TYPE" = "Success Test" ]; then
            SUBJECT="✅ Test Email - PASSED"
            BODY="This is a test email for successful test results."
            COLOR="green"
            TEST_RESULT="PASSED"
          elif [ "$TEST_TYPE" = "Failure Test" ]; then
            SUBJECT="❌ Test Email - FAILED"
            BODY="This is a test email for failed test results."
            COLOR="red"
            TEST_RESULT="FAILED"
          elif [ "$TEST_TYPE" = "Timeout Test" ]; then
            SUBJECT="⏰ Test Email - TIMEOUT"
            BODY="This is a test email for timeout test results."
            COLOR="orange"
            TEST_RESULT="TIMEOUT"
          else
            SUBJECT="❓ Test Email - UNKNOWN"
            BODY="This is a test email for unknown test results."
            COLOR="gray"
            TEST_RESULT="UNKNOWN"
          fi

          HTML_CONTENT="
          <html>
          <body style='font-family: Arial, sans-serif; padding: 20px;'>
            <div style='max-width: 600px; margin: 0 auto; border: 1px solid #ddd; border-radius: 8px; padding: 20px;'>
              <h2 style='color: $COLOR; margin-top: 0;'>$SUBJECT</h2>
              <p><strong>$BODY</strong></p>
              <hr style='border: 1px solid #eee; margin: 20px 0;'>
              <h3 style='color: #333;'>Test Details:</h3>
              <ul style='color: #555;'>
                <li><strong>Test Type:</strong> $TEST_TYPE</li>
                <li><strong>Result:</strong> $TEST_RESULT</li>
                <li><strong>Repository:</strong> ${{ github.repository }}</li>
                <li><strong>Branch:</strong> ${{ github.ref_name }}</li>
                <li><strong>Triggered by:</strong> ${{ github.actor }}</li>
                <li><strong>Execution Time:</strong> $(date -u +"%Y-%m-%d %H:%M:%S UTC")</li>
              </ul>
              <hr style='border: 1px solid #eee; margin: 20px 0;'>
              <p style='color: #666; font-size: 14px;'>
                This is a test email to verify Gmail SMTP functionality for CI/CD notifications.
              </p>
              <p style='color: #666; font-size: 14px;'>
                <a href='https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}' style='color: #0078d4;'>View Workflow Run</a>
              </p>
            </div>
          </body>
          </html>
          "

          echo "$SUBJECT" > email_subject.txt
          echo "$BODY" > email_body.txt
          echo "$COLOR" > email_color.txt
          echo "$HTML_CONTENT" > email_notification.html

      - name: Send Gmail Email to Multiple Recipients
        run: |
          GMAIL_USERNAME="${{ secrets.GMAIL_USERNAME }}"
          GMAIL_APP_PASSWORD="${{ secrets.GMAIL_APP_PASSWORD }}"
          EMAIL_TO="${{ secrets.EMAIL_TO }}"

          SUBJECT=$(cat email_subject.txt)
          HTML_CONTENT=$(cat email_notification.html)
          EMAIL_FROM="$GMAIL_USERNAME"

          echo "From: $EMAIL_FROM" > email_message.txt
          echo "To: $EMAIL_TO" >> email_message.txt
          if [ -n "$EMAIL_CC" ]; then
            echo "Cc: $EMAIL_CC" >> email_message.txt
          fi
          echo "Subject: $SUBJECT" >> email_message.txt
          echo "MIME-Version: 1.0" >> email_message.txt
          echo "Content-Type: text/html; charset=UTF-8" >> email_message.txt
          echo "" >> email_message.txt
          echo "$HTML_CONTENT" >> email_message.txt

          # Build --mail-rcpt arguments
          RCPT_ARGS=""
          IFS=',' read -ra TO_LIST <<< "$EMAIL_TO"
          for RECIPIENT in "${TO_LIST[@]}"; do
            RCPT_ARGS+=" --mail-rcpt \"$RECIPIENT\""
          done

          IFS=',' read -ra CC_LIST <<< "$EMAIL_CC"
          for RECIPIENT in "${CC_LIST[@]}"; do
            RCPT_ARGS+=" --mail-rcpt \"$RECIPIENT\""
          done

          echo "Sending email via Gmail SMTP..."
          eval curl -v --mail-from "$EMAIL_FROM" \
            $RCPT_ARGS \
            --upload-file email_message.txt \
            --ssl-reqd \
            --user "$GMAIL_USERNAME:$GMAIL_APP_PASSWORD" \
            smtp://smtp.gmail.com:587

      - name: Save Test Email Content as Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-email-content
          path: |
            email_notification.html
            email_subject.txt
            email_body.txt
            email_color.txt
            email_message.txt